spring:
  config:
    activate:
      on-profile: dev


#### SSO ####
SSO_SERVER_URL: http://localhost:8080
SSO_REALM_NAME: SUPER_APP
SSO_CLIENT_ID: novel
SSO_CLIENT_SECRET: DRpF1R3jOA9i4ZtxlWGKBPCCnrfHURN0

#### SERVER end point ####
NOVEL_BACKEND_SERVICE: http://localhost:8081